services:
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes: [redis_data:/data]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 2s
      retries: 5
    networks:
      - transcriber-net

  backend:
    build: .
    container_name: backend
    restart: always
    ports: ["5000:5000"]
    env_file: .env
    deploy:
      resources:
        limits: {memory: 1G}
    depends_on:
      redis:
        condition: service_healthy
    command: uvicorn main:app --host 0.0.0.0 --port 5000
    networks:
      - transcriber-net

  worker:
    build: .
    container_name: worker
    restart: always
    env_file: .env
    deploy:
      resources:
        limits: {memory: 2G}
    depends_on:
      redis:
        condition: service_healthy
    command: celery -A celery_app.celery_app worker -l info --concurrency=20
    networks:
      - transcriber-net

  beat:
    build: .
    container_name: beat
    restart: always
    env_file: .env
    deploy:
      resources:
        limits: {memory: 256M}
    depends_on:
      redis:
        condition: service_healthy
    command: celery -A celery_app.celery_app beat -l info
    networks:
      - transcriber-net

volumes:
  redis_data:

networks:
  transcriber-net:
    driver: bridge